name = "openai-cf"                # todo
main = "index.js"
compatibility_date = "2024-05-06"

[ai]
binding = "AI" # i.e. available in your Worker on env.AI

[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "openai-cf-images"
preview_bucket_name = "ai-images"

[vars]
CLOUDFLARE_ACCOUNT_ID = "423f7d160644eba02b8094c8c8726b46" # replace with your own.
MODEL_MAPPER = { "gpt-3.5-turbo" = "@cf/meta/llama-2-7b-chat-int8", "dall-e-3" = "@cf/stabilityai/stable-diffusion-xl-base-1.0" } # Optional

[placement]
mode = "smart"
